### ISSUE TITLE
`match` instead of `matchedRoute` in Guide

### ISSUE THREAD

**Issue by ahwayakchih** [grncdr/web-pockets#9]
Guide uses `match` in its examples, e.g., [route parameters](https://github.com/grncdr/web-pockets/blob/master/guide.md#example-3---route-parameters),  but variable provided by web-pockets is called `matchedRoute` by default.

Shouldn't it use the same name as the one actually used by web-pockets? Or maybe there should be an additional example code that shows how one can create own variable called `match` that is based on `matchedRoute`?

**Comment by grncdr** [comment]
Fixed, thanks for pointing it out!
